Repository PowerGridModel/power-grid-model-ds, pull requests merged in 2025-01, with the labels that each got.

#8 add _build from docs build guide to gitignore
  .gitignore
Labels: improvement

#12 Drop python 3.10
  .github/workflows/build-test-and-sonar.yml
  pyproject.toml
Labels: dependencies

#24 add citations.cff
  .github/workflows/citations.yml
  CITATION.cff
Labels: documentation
