Repository PowerGridModel/power-grid-model-ds, pull requests merged in 2025-02, with the labels that each got.

#30 chore: remove unused/nonfunctional cache on graphcontainer
  src/power_grid_model_ds/_core/model/graphs/container.py
Labels: bug

#16 Feature: add .all_branches property to graph
  VERSION
  src/power_grid_model_ds/_core/model/graphs/models/base.py
  src/power_grid_model_ds/_core/model/graphs/models/rustworkx.py
  tests/unit/model/graphs/test_graph_model.py
Labels: v1.1

#17 Feature: add tmp_remove_nodes method to graph
  src/power_grid_model_ds/_core/model/graphs/models/base.py
  src/power_grid_model_ds/_core/model/graphs/models/rustworkx.py
  tests/unit/model/graphs/test_graph_model.py
Labels: v1.1

#21 Feat: improve downstream node performance
  src/power_grid_model_ds/_core/model/graphs/models/base.py
  src/power_grid_model_ds/_core/model/graphs/models/rustworkx.py
  src/power_grid_model_ds/_core/model/grids/base.py
  tests/unit/model/graphs/test_graph_model.py
  tests/unit/model/grids/test_grid_search.py
Labels: v1.1

#32 Chore: reorganize graph tests
  tests/unit/model/graphs/test_graph_model.py
Labels: v1.1

#25 Add DOI to citations
  CITATION.cff
Labels: documentation

#35 Add DOI to citations + badges
  CITATION.cff
  README.md
Labels: documentation
